### PR TITLE
Swift Package Manager and Linux support

### PR DESCRIPTION
**Pull request by novi**
Added `Package.swift` and Linux support. It passes all tests on macOS and Linux.

And I have made changes to Xcode based project(for Cocoapods, Carthage):

* add `BitcoinKitXcode` compiler flag to change import declaration

`BitcoinKit.xcodeproj` will conflict with Swift Package Manager generated xcodeproj. But it not affects for usage but for development.

### CODE REVIEW

**Comment by usatie** [comment]
Hi, @novi !
Thanks for dropping us this PR.
I am one of the new maintainer of this project.

And I am planning to merge our BIG PR #69 first, but it will surely conflict a large part of you PR.
I'm sorry, can you create the PR again after we merged #69 ?

**Comment by usatie** [comment]
@GitCash send 5000 bits to @novi .
Thanks for dropping us a PR!
This is just a small tip!

**Comment by GitCash** [comment]
Hey **novi**, user **usatie** tipped you **5000 bits** in Bitcoin Cash ( ~ **$3.005** ).

*[Click here to claim it!](https://gitcash.io/claim/novi)*

You can also add the "thumbs down" reaction to **usatie**'s comment above to prevent future tips.

**Comment by usatie** [comment]
@novi now I could resolve the conflict between `novi:work/package-swift` and `yenom:master`.
So can you resolve the current conflict and push the change?
I will merge this PR first, and then, I'll resolve the conflict between `BitcoinCashKit:master` and `yenom:master`!

**Comment by novi** [comment]
Hello. I will check them later.

**Comment by usatie** [comment]
@novi Hi, thank you for your help!

**Comment by usatie** [comment]
@novi Thanks for dropping us PR, we already merged your branch to this branch, so will close this PR.
https://github.com/yenom/BitcoinKit/commit/c01df11b922cbe23460d8bba0ceb2fd4b681198d

I thought your commits going to be included, but it turn out to be not...
So sorry for that.

**Pull request closed without merging**
